pull_request_rules:
  - name: merge automatically when CI passes and PR is approved
    conditions:
        - "#approved-reviews-by >= 0"
    actions:
      comment:
        message: Your PR is in conflict, {{author}}. You should fix it.